- type: job
  id: SecurityGuard
  name: job-name-cctc-justice
  description: job-description-cctc-justice
  playTimeTracker: JobSecurityGuard
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 36000 # Frontier - 10 hrs
  startingGear: SecurityGuardGear
  alwaysUseSpawner: true
  icon: "JobIconCCTCJustice"
  supervisors: job-supervisors-sr
  assignedCompany: Colonial
  weight: 80
  displayWeight: 20 # Second from the bottom
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  - Mercenary
  - Captain
  - Frontier
  special:
  - !type:AddComponentSpecial
    components:
    - type: ChatRank
      rank: cctc-justice
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ] # Mono - remove TSFMC implant
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: SecurityGuardGear
  equipment:
    pocket1: WeaponEnergyGunLawbringer
  storage:
    back:
    - EncryptionKeyService
    - EncryptionKeySecurity
    - ShipVoucherFrontierGuard
